version: '3.9'

# Use this spec during development

services:
  # Instance used for dev application instance.
  postgres:
    image: postgres:16-alpine
    shm_size: 4g
    cpu_count: 4
    user: root
    volumes:
      - ./.pgdata/database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=momo
      - PGDATA=/var/lib/postgresql/data/db-files/
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - momo

  # Instance used for unit tests
  postgres-test:
    image: postgres:16-alpine
    shm_size: 2g
    cpu_count: 2
    user: root
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=unit_test
    expose:
      - 6543
    ports:
      - "6543:5432"
    networks:
      - momo

networks:
  momo:
